etape1: etape1.c liste.h
	gcc -Wall -Werror -Wextra -o etape1 etape1.c

etape2: etape2.c liste.h liste.c
	gcc -Wall -Werror -Wextra -o etape2 etape2.c liste.c

etape3: etape3.c liste.h liste.c
	gcc -Wall -Werror -Wextra -o etape3 etape3.c liste.c

etape4: etape4.c liste.h liste.c
	gcc -Wall -Werror -Wextra -o etape4 etape4.c liste.c

clean:
	rm etape1
	rm etape2
	rm etape3
	rm etape4	