liste1: liste1.c
	gcc -Wall -Werror -Wextra -o liste1 liste1.c

liste2: liste2.c
	gcc -Wall -Werror -Wextra -o liste2 liste2.c

liste3: liste3.c
	gcc -Wall -Werror -Wextra -o liste3 liste3.c

liste4: liste4.c
	gcc -Wall -Werror -Wextra -o liste4 liste4.c

clean:
	rm liste1
	rm liste2
	rm liste3
	rm liste4	