tri0 : tri0.c reference.c  reference.h
	gcc -Wall -Werror -Wextra -o tri0 tri0.c reference.c

tri1 : tri1.c reference.c  reference.h
	gcc -Wall -Werror -Wextra -o tri1 tri1.c reference.c

tri2 : tri2.c reference.c  reference.h
	gcc -Wall -Werror -Wextra -o tri2 tri2.c reference.c

tri3 : tri3.c reference.c  reference.h
	gcc -Wall -Werror -Wextra -o tri3 tri3.c reference.c

tri4 : tri4.c reference.c  reference.h
	gcc -Wall -Werror -Wextra -o tri4 tri4.c reference.c

tri5 : tri5.c reference.c  reference.h
	gcc -Wall -Werror -Wextra -o tri5 tri5.c reference.c

test01 : test01.c
	gcc -Wall -Werror -Wextra -o test01 test01.c

clean:
	rm tri1
	rm tri2
	rm tri3	
	rm tri4	
	rm tri5
	rm test01